import type { ScenarioDefinition } from "@/lib/scenario/types";
import playground from "@/assets/scene-77.png.asset.json";
import veranda from "@/assets/scene-78.png.asset.json";
import repayment from "@/assets/scene-79.png.asset.json";

// "The School Reopening Adventure" — branching data only. No UI here.
export const schoolReopeningScenario: ScenarioDefinition = {
  id: "kwame-request",
  track: "save",
  title: "Kwame's Request",
  subtitle: "The School Reopening Adventure",
  description:
    "A friend asks to borrow money while you are saving for your school bag. Every choice changes what happens next.",
  totalDays: 14,
  goalLabel: "School Bag Goal",
  goalTarget: 80,
  startingAvailable: 22,
  startingSaved: 45,
  startNodeId: "kwame-request",
  competencies: ["borrowing-lending", "goal-setting", "saving", "financial-resilience"],
  closingReflection:
    "Money choices keep going after the day you make them. Noticing what happens next is what good money managers do.",
  intro: {
    title: "Kwame's Request",
    body: "You are on Day 6 of the School Reopening Adventure. You have money in your pocket and money in your savings box. A friend is about to ask you for help.",
    image: playground.url,
    cta: "Start the story",
  },
  nodes: [
    {
      id: "kwame-request",
      day: 6,
      topic: "Friendship & Money Dilemma",
      place: "Playground",
      title: "Kwame's Request",
      situation:
        "Kwame needs GH₵10 and promises to pay you back on Friday. You are also saving for your school bag.",
      question: "What would you like to do?",
      image: playground.url,
      imageCaption: "Under the mango tree at Accra D.A. Basic School",
      tip: "There are no wrong answers. Different choices lead to different real-life situations!",
      choices: [
        {
          id: "lend-10",
          label: "Lend Kwame GH₵10",
          description: "Help your friend with everything he asked for.",
          icon: "🤝",
          effect: {
            available: -10,
            flags: { lentToKwame: 10 },
            competencies: { "borrowing-lending": 1 },
          },
          consequence: {
            decisionChip: "Decision: You lent Kwame GH₵10",
            headline: "Here's what happened",
            title: "A kind choice and a real trade-off",
            body: "Helping someone can be important. But now you have less money available until Kwame pays you back.",
            image: veranda.url,
            imageCaption: "Veranda Reflections",
            ledgerNote: "−GH₵10 for Kwame",
            laterHint: "Financial promises take time. Let's see what happens on Friday!",
          },
          schedule: { inDays: 3, nodeId: "repayment-day" },
          next: "quiet-day",
        },
        {
          id: "lend-5",
          label: "Lend Kwame GH₵5",
          description: "Share half and keep the rest available for your goal.",
          icon: "⚖️",
          effect: {
            available: -5,
            flags: { lentToKwame: 5 },
            competencies: { "borrowing-lending": 2, "goal-setting": 1 },
          },
          consequence: {
            decisionChip: "Decision: You lent Kwame GH₵5",
            headline: "Here's what happened",
            title: "Helping and still holding your plan",
            body: "Kwame thanked you and found the rest from his brother. You kept part of your pocket money for your own plan.",
            image: veranda.url,
            imageCaption: "Veranda Reflections",
            ledgerNote: "−GH₵5 for Kwame",
            laterHint: "Kwame said he will bring your cedis back on Friday.",
          },
          schedule: { inDays: 3, nodeId: "repayment-day" },
          next: "quiet-day",
        },
        {
          id: "keep",
          label: "Keep the money for my goal",
          description: "Politely protect all your cedis for the school bag.",
          icon: "🛡️",
          effect: {
            competencies: { "goal-setting": 2, saving: 1 },
          },
          consequence: {
            decisionChip: "Decision: You kept your cedis",
            headline: "Here's what happened",
            title: "Protecting your promise to yourself",
            body: "You told Kwame kindly that your money is already promised to your school bag. He understood and asked his uncle instead.",
            image: veranda.url,
            imageCaption: "Veranda Reflections",
            ledgerNote: "No change",
            laterHint: "Your goal is still on track. Something else is coming on Day 9.",
          },
          next: "market-offer",
        },
      ],
    },
    {
      id: "quiet-day",
      day: 7,
      topic: "Everyday Choice",
      place: "School gate",
      title: "A warm afternoon",
      situation:
        "Waiting for your mother at the gate, the ice-kenkey seller passes by. GH₵2 would buy a cold treat.",
      question: "What do you do with your pocket money today?",
      image: playground.url,
      choices: [
        {
          id: "treat",
          label: "Buy the treat for GH₵2",
          description: "Enjoy something small today.",
          icon: "🍧",
          effect: { available: -2, competencies: { "spending-decisions": 1 } },
          consequence: {
            decisionChip: "Decision: A GH₵2 treat",
            headline: "Here's what happened",
            title: "Enjoying a little, keeping the rest",
            body: "You enjoyed your treat and still have money in your pocket. Small spending is fine when your goal money stays safe.",
            ledgerNote: "−GH₵2",
          },
        },
        {
          id: "save-2",
          label: "Put GH₵2 in the savings box",
          description: "Move a little more towards the school bag.",
          icon: "🐖",
          effect: { transferToSaved: 2, competencies: { saving: 2 } },
          consequence: {
            decisionChip: "Decision: GH₵2 to the savings box",
            headline: "Here's what happened",
            title: "Small and regular wins",
            body: "Two cedis does not feel like much today, but added week after week it moves your school bag closer.",
            ledgerNote: "+GH₵2 saved",
          },
        },
      ],
    },
    {
      id: "market-offer",
      day: 9,
      topic: "Spending Decision",
      place: "Makola Market",
      title: "A jersey at the market",
      situation:
        "A bright Black Stars jersey is on sale for GH₵25. Your school bag money is sitting in your savings box.",
      question: "What would you like to do?",
      image: playground.url,
      tip: "Think about what you promised yourself on Day 3.",
      choices: [
        {
          id: "buy",
          label: "Buy the jersey",
          description: "Take GH₵25 from the savings box.",
          icon: "👕",
          effect: { saved: -25, competencies: { "spending-decisions": 1 } },
          consequence: {
            decisionChip: "Decision: You bought the jersey",
            headline: "Here's what happened",
            title: "A happy day and a longer road",
            body: "The jersey is lovely. Your school bag is further away now, so you will need more saving days before reopening.",
            ledgerNote: "−GH₵25 saved",
            laterHint: "You can still catch up with steady saving.",
          },
          ending: "recovered",
        },
        {
          id: "wait",
          label: "Stay the course",
          description: "Keep the savings box untouched.",
          icon: "🎯",
          effect: { competencies: { "goal-setting": 2, "financial-resilience": 1 } },
          consequence: {
            decisionChip: "Decision: You stayed on plan",
            headline: "Here's what happened",
            title: "You remembered your goal",
            body: "You walked past the stall. Your school bag money is complete and waiting for reopening day.",
            ledgerNote: "No change",
          },
          ending: "on-track",
        },
      ],
    },
    {
      id: "repayment-day",
      day: 9,
      topic: "Repayment Dilemma",
      place: "School veranda",
      title: "Remember the money you lent Kwame?",
      situation:
        "Kwame planned to return your cedis today, but he only has part of it. He wants to give you the rest next week.",
      question: "What would you like to do next?",
      image: repayment.url,
      imageCaption: "Partial repayment at the veranda",
      imageBadge: "Repayment day",
      quote: {
        speaker: "Kwame says",
        text: "Thank you so much for helping me on Tuesday. I only have part of it today, but I will bring the rest next week.",
      },
      tip: "When people borrow, repayments are sometimes delayed or partial. Good money managers plan for that.",
      choices: [
        {
          id: "to-savings",
          label: "Put what he returned into my savings box",
          description: "Send it straight to the school bag goal.",
          icon: "🐖",
          effect: { saved: 5, competencies: { saving: 2, "borrowing-lending": 1 } },
          consequence: {
            decisionChip: "Decision: Repayment went to savings",
            headline: "Here's what happened",
            title: "Straight to your goal",
            body: "The returned cedis went into the box right away, so they cannot quietly disappear into small spending.",
            ledgerNote: "+GH₵5 saved",
          },
          next: "market-offer",
        },
        {
          id: "to-pocket",
          label: "Keep it as pocket money",
          description: "Hold it for pencils or snacks this week.",
          icon: "👛",
          effect: { available: 5, competencies: { "tracking-money": 1 } },
          consequence: {
            decisionChip: "Decision: Repayment stays in pocket",
            headline: "Here's what happened",
            title: "Ready for this week",
            body: "You now have more available for school needs. Remember that pocket money disappears faster than box money.",
            ledgerNote: "+GH₵5 available",
          },
          next: "market-offer",
        },
        {
          id: "agree-date",
          label: "Agree a day for the rest",
          description: "Talk with Kwame about when the rest will arrive.",
          icon: "💬",
          effect: {
            available: 5,
            competencies: { "borrowing-lending": 3, "financial-resilience": 1 },
          },
          consequence: {
            decisionChip: "Decision: You agreed a clear day",
            headline: "Here's what happened",
            title: "A clear plan beats a vague promise",
            body: "You took what Kwame had and you both wrote down the day the rest will come. Now you can plan your school bag purchase.",
            ledgerNote: "+GH₵5 available",
            laterHint: "Clear agreements protect friendships as well as money.",
          },
          next: "market-offer",
        },
      ],
    },
  ],
  endings: [
    {
      id: "on-track",
      title: "Your goal is still standing",
      body: "You made kind choices and still protected the money you promised to your school bag.",
      reflection: "Which decision felt hardest? What made you stick with your plan?",
    },
    {
      id: "recovered",
      title: "A detour, not a dead end",
      body: "You spent some of your goal money and learned how that feels. Saving again from here is completely possible.",
      reflection: "What would you do differently if the same stall appeared tomorrow?",
    },
  ],
};
