/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChildRouteRouteImport } from './routes/child/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ChildHomeRouteImport } from './routes/child/home'
import { Route as ChildLearnRouteImport } from './routes/child/learn'
import { Route as ChildLessonLessonIdRouteImport } from './routes/child/lesson.$lessonId'
import { Route as ChildScenarioScenarioIdRouteImport } from './routes/child/scenario.$scenarioId'
import { Route as AuthenticatedLearnChildIdIndexRouteImport } from './routes/_authenticated/learn.$childId.index'
import { Route as AuthenticatedLearnChildIdSummaryRouteImport } from './routes/_authenticated/learn.$childId.summary'
import { Route as AuthenticatedLearnChildIdAssessmentAssessmentIdRouteImport } from './routes/_authenticated/learn.$childId.assessment.$assessmentId'
import { Route as AuthenticatedLearnChildIdLessonLessonIdRouteImport } from './routes/_authenticated/learn.$childId.lesson.$lessonId'
import { Route as AuthenticatedLearnChildIdScenarioScenarioIdRouteImport } from './routes/_authenticated/learn.$childId.scenario.$scenarioId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildRouteRoute = ChildRouteRouteImport.update({
  id: '/child',
  path: '/child',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ChildHomeRoute = ChildHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ChildRouteRoute,
} as any)
const ChildLearnRoute = ChildLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => ChildRouteRoute,
} as any)
const ChildLessonLessonIdRoute = ChildLessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => ChildRouteRoute,
} as any)
const ChildScenarioScenarioIdRoute = ChildScenarioScenarioIdRouteImport.update({
  id: '/scenario/$scenarioId',
  path: '/scenario/$scenarioId',
  getParentRoute: () => ChildRouteRoute,
} as any)
const AuthenticatedLearnChildIdIndexRoute =
  AuthenticatedLearnChildIdIndexRouteImport.update({
    id: '/learn/$childId/',
    path: '/learn/$childId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnChildIdSummaryRoute =
  AuthenticatedLearnChildIdSummaryRouteImport.update({
    id: '/learn/$childId/summary',
    path: '/learn/$childId/summary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnChildIdAssessmentAssessmentIdRoute =
  AuthenticatedLearnChildIdAssessmentAssessmentIdRouteImport.update({
    id: '/learn/$childId/assessment/$assessmentId',
    path: '/learn/$childId/assessment/$assessmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnChildIdLessonLessonIdRoute =
  AuthenticatedLearnChildIdLessonLessonIdRouteImport.update({
    id: '/learn/$childId/lesson/$lessonId',
    path: '/learn/$childId/lesson/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnChildIdScenarioScenarioIdRoute =
  AuthenticatedLearnChildIdScenarioScenarioIdRouteImport.update({
    id: '/learn/$childId/scenario/$scenarioId',
    path: '/learn/$childId/scenario/$scenarioId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/child': typeof ChildRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/child/home': typeof ChildHomeRoute
  '/child/learn': typeof ChildLearnRoute
  '/child/lesson/$lessonId': typeof ChildLessonLessonIdRoute
  '/child/scenario/$scenarioId': typeof ChildScenarioScenarioIdRoute
  '/learn/$childId/summary': typeof AuthenticatedLearnChildIdSummaryRoute
  '/learn/$childId/': typeof AuthenticatedLearnChildIdIndexRoute
  '/learn/$childId/assessment/$assessmentId': typeof AuthenticatedLearnChildIdAssessmentAssessmentIdRoute
  '/learn/$childId/lesson/$lessonId': typeof AuthenticatedLearnChildIdLessonLessonIdRoute
  '/learn/$childId/scenario/$scenarioId': typeof AuthenticatedLearnChildIdScenarioScenarioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/child': typeof ChildRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/child/home': typeof ChildHomeRoute
  '/child/learn': typeof ChildLearnRoute
  '/child/lesson/$lessonId': typeof ChildLessonLessonIdRoute
  '/child/scenario/$scenarioId': typeof ChildScenarioScenarioIdRoute
  '/learn/$childId/summary': typeof AuthenticatedLearnChildIdSummaryRoute
  '/learn/$childId': typeof AuthenticatedLearnChildIdIndexRoute
  '/learn/$childId/assessment/$assessmentId': typeof AuthenticatedLearnChildIdAssessmentAssessmentIdRoute
  '/learn/$childId/lesson/$lessonId': typeof AuthenticatedLearnChildIdLessonLessonIdRoute
  '/learn/$childId/scenario/$scenarioId': typeof AuthenticatedLearnChildIdScenarioScenarioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/child': typeof ChildRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/child/home': typeof ChildHomeRoute
  '/child/learn': typeof ChildLearnRoute
  '/child/lesson/$lessonId': typeof ChildLessonLessonIdRoute
  '/child/scenario/$scenarioId': typeof ChildScenarioScenarioIdRoute
  '/_authenticated/learn/$childId/summary': typeof AuthenticatedLearnChildIdSummaryRoute
  '/_authenticated/learn/$childId/': typeof AuthenticatedLearnChildIdIndexRoute
  '/_authenticated/learn/$childId/assessment/$assessmentId': typeof AuthenticatedLearnChildIdAssessmentAssessmentIdRoute
  '/_authenticated/learn/$childId/lesson/$lessonId': typeof AuthenticatedLearnChildIdLessonLessonIdRoute
  '/_authenticated/learn/$childId/scenario/$scenarioId': typeof AuthenticatedLearnChildIdScenarioScenarioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/child'
    | '/auth'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard'
    | '/child/home'
    | '/child/learn'
    | '/child/lesson/$lessonId'
    | '/child/scenario/$scenarioId'
    | '/learn/$childId/summary'
    | '/learn/$childId/'
    | '/learn/$childId/assessment/$assessmentId'
    | '/learn/$childId/lesson/$lessonId'
    | '/learn/$childId/scenario/$scenarioId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/child'
    | '/auth'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard'
    | '/child/home'
    | '/child/learn'
    | '/child/lesson/$lessonId'
    | '/child/scenario/$scenarioId'
    | '/learn/$childId/summary'
    | '/learn/$childId'
    | '/learn/$childId/assessment/$assessmentId'
    | '/learn/$childId/lesson/$lessonId'
    | '/learn/$childId/scenario/$scenarioId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/child'
    | '/auth'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/child/home'
    | '/child/learn'
    | '/child/lesson/$lessonId'
    | '/child/scenario/$scenarioId'
    | '/_authenticated/learn/$childId/summary'
    | '/_authenticated/learn/$childId/'
    | '/_authenticated/learn/$childId/assessment/$assessmentId'
    | '/_authenticated/learn/$childId/lesson/$lessonId'
    | '/_authenticated/learn/$childId/scenario/$scenarioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ChildRouteRoute: typeof ChildRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child': {
      id: '/child'
      path: '/child'
      fullPath: '/child'
      preLoaderRoute: typeof ChildRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/child/home': {
      id: '/child/home'
      path: '/home'
      fullPath: '/child/home'
      preLoaderRoute: typeof ChildHomeRouteImport
      parentRoute: typeof ChildRouteRoute
    }
    '/child/learn': {
      id: '/child/learn'
      path: '/learn'
      fullPath: '/child/learn'
      preLoaderRoute: typeof ChildLearnRouteImport
      parentRoute: typeof ChildRouteRoute
    }
    '/child/lesson/$lessonId': {
      id: '/child/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/child/lesson/$lessonId'
      preLoaderRoute: typeof ChildLessonLessonIdRouteImport
      parentRoute: typeof ChildRouteRoute
    }
    '/child/scenario/$scenarioId': {
      id: '/child/scenario/$scenarioId'
      path: '/scenario/$scenarioId'
      fullPath: '/child/scenario/$scenarioId'
      preLoaderRoute: typeof ChildScenarioScenarioIdRouteImport
      parentRoute: typeof ChildRouteRoute
    }
    '/_authenticated/learn/$childId/': {
      id: '/_authenticated/learn/$childId/'
      path: '/learn/$childId'
      fullPath: '/learn/$childId/'
      preLoaderRoute: typeof AuthenticatedLearnChildIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$childId/summary': {
      id: '/_authenticated/learn/$childId/summary'
      path: '/learn/$childId/summary'
      fullPath: '/learn/$childId/summary'
      preLoaderRoute: typeof AuthenticatedLearnChildIdSummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$childId/assessment/$assessmentId': {
      id: '/_authenticated/learn/$childId/assessment/$assessmentId'
      path: '/learn/$childId/assessment/$assessmentId'
      fullPath: '/learn/$childId/assessment/$assessmentId'
      preLoaderRoute: typeof AuthenticatedLearnChildIdAssessmentAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$childId/lesson/$lessonId': {
      id: '/_authenticated/learn/$childId/lesson/$lessonId'
      path: '/learn/$childId/lesson/$lessonId'
      fullPath: '/learn/$childId/lesson/$lessonId'
      preLoaderRoute: typeof AuthenticatedLearnChildIdLessonLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$childId/scenario/$scenarioId': {
      id: '/_authenticated/learn/$childId/scenario/$scenarioId'
      path: '/learn/$childId/scenario/$scenarioId'
      fullPath: '/learn/$childId/scenario/$scenarioId'
      preLoaderRoute: typeof AuthenticatedLearnChildIdScenarioScenarioIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLearnChildIdSummaryRoute: typeof AuthenticatedLearnChildIdSummaryRoute
  AuthenticatedLearnChildIdIndexRoute: typeof AuthenticatedLearnChildIdIndexRoute
  AuthenticatedLearnChildIdAssessmentAssessmentIdRoute: typeof AuthenticatedLearnChildIdAssessmentAssessmentIdRoute
  AuthenticatedLearnChildIdLessonLessonIdRoute: typeof AuthenticatedLearnChildIdLessonLessonIdRoute
  AuthenticatedLearnChildIdScenarioScenarioIdRoute: typeof AuthenticatedLearnChildIdScenarioScenarioIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLearnChildIdSummaryRoute: AuthenticatedLearnChildIdSummaryRoute,
  AuthenticatedLearnChildIdIndexRoute: AuthenticatedLearnChildIdIndexRoute,
  AuthenticatedLearnChildIdAssessmentAssessmentIdRoute:
    AuthenticatedLearnChildIdAssessmentAssessmentIdRoute,
  AuthenticatedLearnChildIdLessonLessonIdRoute:
    AuthenticatedLearnChildIdLessonLessonIdRoute,
  AuthenticatedLearnChildIdScenarioScenarioIdRoute:
    AuthenticatedLearnChildIdScenarioScenarioIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ChildRouteRouteChildren {
  ChildHomeRoute: typeof ChildHomeRoute
  ChildLearnRoute: typeof ChildLearnRoute
  ChildLessonLessonIdRoute: typeof ChildLessonLessonIdRoute
  ChildScenarioScenarioIdRoute: typeof ChildScenarioScenarioIdRoute
}

const ChildRouteRouteChildren: ChildRouteRouteChildren = {
  ChildHomeRoute: ChildHomeRoute,
  ChildLearnRoute: ChildLearnRoute,
  ChildLessonLessonIdRoute: ChildLessonLessonIdRoute,
  ChildScenarioScenarioIdRoute: ChildScenarioScenarioIdRoute,
}

const ChildRouteRouteWithChildren = ChildRouteRoute._addFileChildren(
  ChildRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ChildRouteRoute: ChildRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
